// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type UserLoginRespone struct {
	Token string `json:"token"`
}
